# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
mainlogo: KIDO
title: KIDO BLOG
subtitle: Do not fear the unknown.
author: Kido
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.kido.site
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: Kido的博客 | Kido's Blog
header-img: img/home-bg-02.jpg
email: woshidianshu@gmail.com
description: ""
keyword: ""


# SNS settings
# RSS: false
weibo_username:     1882973501
zhihu_username:     dian-Kido
github_username:    Dian-Kido
twitter_username:
facebook_username:
linkedin_username:

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
disqus_username: disqus_FavHhu4Kfn
disqus_sitename: blog-kido-site

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share:                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id: 14296f5fec38bbac68ddad04e4cf4b72
# Google Analytics
ga_track_id: UA-140410086-2            # Format: UA-xxxxxx-xx
ga_domain:


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "泡面大厨"
sidebar-avatar: img/blog-avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0             # A tag will be featured if the size of it is more than this condition value


# Friends
friends: [
{
  title: "陶笛日记",
  href: "https://ocarina-diary.com/blogs/"
},
{
  title: "Peter Fan",
  href: "https://goffea.com/"
},
{
  title: "TianShouzhi",
  href: "http://www.tianshouzhi.com/"
},
{
  title: "Breeze924",
  href: "https://breeze924.github.io/"
}
]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: i_dont_wanna_use_default_archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huxblog

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://{*****token*****}@github.com/Dian-Kido/Dian-Kido.github.io.git
  branch: master
